opcua_set_value:
  description: Set a value to an OPC UA node.
  fields:
    hub:
      required: true
      description: A specified hub that is configured inside the integration.
      example: "example_hub"
      selector:
        text:
    node_id:
      description: The Node ID of the OPC UA node to write to.
      required: true
      example: "ns=2;s=SomeNodeId"
      selector:
        text:
    value:
      description: Scalar value to write. For DateTime use ISO 8601 with a timezone (for example 2026-09-14T18:30:00+02:00).
      required: true
      example: "0"
      selector:
        text:
